### ISSUE TITLE
Make it possible to login with token

### ISSUE THREAD

**Issue by Miepee** [Riesi/matrix_latex_bot#5]
Documentation has an example of how to do that:
https://docs.rs/matrix-sdk/0.6.2/matrix_sdk/struct.Client.html#method.login_token

**Comment by Riesi** [comment]
the bot now supports logging in via a token after initial authentication with username and password via cli interation
it also asks for password to encrypt the encryption store with, if `MATRIX_BOT_CRYPTO_PW` is not set to the desired password value already

I would close this after its documented in a readme
