### ISSUE TITLE
Remove hardcoded limit to have the command names be longer than 5 chars

### ISSUE THREAD

**Issue by Miepee** [Riesi/matrix_latex_bot#7]
in main.rs
`let command_slice = if command_message.len() >=5 {&command_message[0..5]} else {command_message};`
Not quite sure why it's there tbh

**Comment by Riesi** [comment]
I think the limit is there to reduce the amount of computation of the string operations. Because the input string could be pretty long and searching for a space would take a lot of time. But maybe we can change the limit to the longest defined command.

**Comment by Miepee** [comment]
> searching for a space would take a lot of time

I don't think it'd be very significant. Not that familiar with rust, but I would assume that searching within a string should be fairly optimized.

**Comment by Riesi** [comment]
yes, but why search through 10000characters when you know your commands are i.e. 6chars at max
thats probably significant
